apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-data
spec:
  selector:
    matchLabels:
      service: hadoop-data
  replicas: 3
  serviceName: hadoop-data
  template:
    metadata:
      labels:
        service: hadoop-data
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - worker
                - key: type
                  operator: In
                  values:
                    - on-premise
                    - cloud
                - key: provider
                  operator: In
                  values:
                    - host
                    - aws
                    - azure
                - key: service
                  operator: In
                  values:
                    - virtualbox
                    - ec2
                    - eks
                    - aks
                - key: region
                  operator: In
                  values:
                    - local
                    - ap-south-1
                    - centralindia
                - key: availability_zone
                  operator: In
                  values:
                    - local-c
                    - ap-south-1b
                    - zone-2
      containers:
        - name: main
          image: sloopstash/hadoop:v2.10.1
          imagePullPolicy: Always
          command: ["/usr/bin/supervisord"]
          args: ["-c", "/etc/supervisord.conf"]
          env:
            - name: JAVA_HOME
              value: /usr/java/jdk1.8.0_131/jre
            - name: HADOOP_HOME
              value: /usr/local/lib/hadoop
            - name: HADOOP_CONF_DIR
              value: /usr/local/lib/hadoop/etc/hadoop
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk1.8.0_131/jre/bin:/usr/local/lib/hadoop/bin
          volumeMounts:
            - name: hadoop-data
              mountPath: /opt/hadoop/data
            - name: hadoop-log
              mountPath: /opt/hadoop/log
            - name: hadoop-tmp
              mountPath: /opt/hadoop/tmp
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: hadoop-conf
              mountPath: /opt/hadoop/system/supervisor.ini
              subPath: supervisor.ini
            - name: hadoop-conf
              mountPath: /opt/hadoop/conf/env.sh
              subPath: env.sh
            - name: hadoop-conf
              mountPath: /opt/hadoop/conf/core-site.xml
              subPath: core-site.xml
            - name: hadoop-conf
              mountPath: /opt/hadoop/conf/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hadoop-script
              mountPath: /opt/hadoop/script/start.sh
              subPath: start.sh
            - name: hadoop-script
              mountPath: /opt/hadoop/script/stop.sh
              subPath: stop.sh
          ports:
            - containerPort: 9000
            - containerPort: 50070
      volumes:
        - name: hadoop-data
          persistentVolumeClaim:
            claimName: hadoop-data
        - name: hadoop-log
          persistentVolumeClaim:
            claimName: hadoop-log
        - name: hadoop-conf
          configMap:
            name: hadoop-data
            items:
              - key: supervisor.ini
                path: supervisor.ini
              - key: env.sh
                path: env.sh
              - key: core-site.xml
                path: core-site.xml
              - key: hdfs-site.xml
                path: hdfs-site.xml
        - name: hadoop-script
          configMap:
            name: hadoop-data
            defaultMode: 0755
            items:
              - key: start.sh
                path: start.sh
              - key: stop.sh
                path: stop.sh
        - name: hadoop-tmp
          persistentVolumeClaim:
            claimName: hadoop-tmp
        - name: supervisor-server
          configMap:
            name: hadoop-data
  volumeClaimTemplates:
    - metadata:
        name: hadoop-data
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: hadoop-log
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: hadoop-tmp
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
