apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hadoop-name
spec:
  selector:
    matchLabels:
      service: hadoop-name
  replicas: 1
  serviceName: hadoop-name
  template:
    metadata:
      labels:
        service: hadoop-name
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - worker
                - key: type
                  operator: In
                  values:
                    - on-premise
                    - cloud
                - key: provider
                  operator: In
                  values:
                    - host
                    - aws
                    - azure
                - key: service
                  operator: In
                  values:
                    - virtualbox
                    - ec2
                    - eks
                    - aks
                - key: region
                  operator: In
                  values:
                    - local
                    - ap-south-1
                    - centralindia
                - key: availability_zone
                  operator: In
                  values:
                    - local-b
                    - ap-south-1b
                    - zone-2
      containers:
        - name: main
          image: sloopstash/hadoop:v2.10.1
          imagePullPolicy: Always
          command: ["/usr/bin/supervisord"]
          args: ["-c", "/etc/supervisord.conf"]
          env:
            - name: JAVA_HOME
              value: /usr/java/jdk1.8.0_131/jre
            - name: HADOOP_HOME
              value: /usr/local/lib/hadoop
            - name: HADOOP_CONF_DIR
              value: /usr/local/lib/hadoop/etc/hadoop
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/jdk1.8.0_131/jre/bin:/usr/local/lib/hadoop/bin
          volumeMounts:
            - name: hadoop-data
              mountPath: /opt/hadoop/data
            - name: hadoop-log
              mountPath: /opt/hadoop/log
            - name: hadoop-script
              mountPath: /opt/hadoop/script
            - name: hadoop-tmp
              mountPath: /opt/hadoop/tmp
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: hadoop-supervisor
              mountPath: /opt/hadoop/system/supervisor.ini
              subPath: hadoop-supervisor
            - name: hadoop-env
              mountPath: /opt/hadoop/conf/env.sh
              subPath: hadoop-env
            - name: hadoop-core-site
              mountPath: /opt/hadoop/conf/core-site.xml
              subPath: hadoop-core-site
            - name: hadoop-hdfs-site
              mountPath: /opt/hadoop/conf/hdfs-site.xml
              subPath: hadoop-hdfs-site
          ports:
            - containerPort: 9000
            - containerPort: 50070
      volumes:
        - name: hadoop-data
          persistentVolumeClaim:
            claimName: data
        - name: hadoop-log
          persistentVolumeClaim:
            claimName: log
        - name: hadoop-script
          configMap:
            name: hadoop-name
        - name: hadoop-tmp
          persistentVolumeClaim:
            claimName: tmp
        - name: supervisor-server
          configMap:
            name: hadoop-name
        - name: hadoop-supervisor
          configMap:
            name: hadoop-name
        - name: hadoop-env
          configMap:
            name: hadoop-name
        - name: hadoop-core-site
          configMap:
            name: hadoop-name
        - name: hadoop-hdfs-site
          configMap:
            name: hadoop-name
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: log
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
    - metadata:
        name: tmp
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
