apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    service: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: nginx
