apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-controller
spec:
  selector:
    matchLabels:
      service: kafka-controller
  replicas: 3
  serviceName: kafka-controller
  template:
    metadata:
      labels:
        service: kafka-controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: node-role.kubernetes.io/worker
                  operator: In
                  values:
                    - worker
                - key: type
                  operator: In
                  values:
                    - on-premise
                    - cloud
                - key: provider
                  operator: In
                  values:
                    - host
                    - aws
                    - azure
                - key: service
                  operator: In
                  values:
                    - virtualbox
                    - ec2
                    - eks
                    - aks
                - key: region
                  operator: In
                  values:
                    - local
                    - ap-south-1
                    - centralindia
                - key: availability_zone
                  operator: In
                  values:
                    - local-b
                    - ap-south-1b
                    - zone-2
      containers:
        - name: main
          image: sloopstash/kafka:v3.2.1
          imagePullPolicy: Always
          command: ["/usr/bin/supervisord"]
          args: ["-c", "/etc/supervisord.conf"]
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
          volumeMounts:
            - name: kafka-data
              mountPath: /opt/kafka/data
            - name: kafka-log
              mountPath: /opt/kafka/log
            - name: kafka-script
              mountPath: /opt/kafka/script
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
              subPath: supervisor-server
            - name: kafka-supervisor
              mountPath: /opt/kafka/system/supervisor.ini
              subPath: kafka-supervisor
            - name: kafka-server
              mountPath: /opt/kafka/conf/server-reference.conf
              subPath: kafka-server
          ports:
            - containerPort: 9093
          livenessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9093
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: data
        - name: kafka-log
          persistentVolumeClaim:
            claimName: log
        - name: kafka-script
          configMap:
            name: kafka-controller
        - name: supervisor-server
          configMap:
            name: kafka-controller
        - name: kafka-supervisor
          configMap:
            name: kafka-controller
        - name: kafka-server
          configMap:
            name: kafka-controller
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: log
      spec:
        storageClassName: standard
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
